# Generated by Django 5.0.7 on 2024-08-07 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycarrier', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='adminregistation',
            new_name='Adminregistration',
        ),
    ]
