# Generated by Django 5.0.7 on 2024-08-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycarrier', '0003_rename_choose_adminregistration_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USERNAME', models.CharField(max_length=100)),
                ('PASSWORD', models.CharField(max_length=100)),
                ('EMAIL', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User_jobseeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USERNAME', models.CharField(max_length=100)),
                ('PASSWORD', models.CharField(max_length=100)),
                ('EMAIL', models.EmailField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='adminregistration',
            name='USERTYPE',
        ),
    ]
