# Generated by Django 5.0.7 on 2024-08-08 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycarrier', '0004_user_employer_user_jobseeker_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adminregistration',
        ),
    ]
