# Generated by Django 5.0.7 on 2024-08-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycarrier', '0006_employer_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer_details',
            name='COMPANY_LOGO',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pfp'),
        ),
        migrations.AlterField(
            model_name='employer_details',
            name='EMPLOYER_EMAIL',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employer_details',
            name='EMPLOYER_IMAGE',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pfp'),
        ),
    ]
