# Generated by Django 5.0.7 on 2024-08-14 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycarrier', '0007_alter_employer_details_company_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer_details',
            name='EMPLOYER_EMAIL',
        ),
    ]
