# Generated by Django 5.0.7 on 2024-08-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycarrier', '0008_remove_employer_details_employer_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='employer_details',
        ),
        migrations.AddField(
            model_name='user_employer',
            name='COMPANY_LOGO',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pfp'),
        ),
        migrations.AddField(
            model_name='user_employer',
            name='COMPANY_NAME',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_employer',
            name='EMPLOYER_AGE',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_employer',
            name='EMPLOYER_IMAGE',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pfp'),
        ),
        migrations.AddField(
            model_name='user_employer',
            name='EMPLOYER_JOB_NATURE',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_employer',
            name='EMPLOYER_LOCATION',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_employer',
            name='EMPLOYER_NAME',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_employer',
            name='EMPLOYER_PHONE',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_employer',
            name='EMPLOYER_PROFESSION',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_employer',
            name='EMPLOYER_STATE',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
