# Generated by Django 5.0.7 on 2024-08-19 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycarrier', '0010_employer_post_a_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer_post_a_job',
            name='JOB_WEBSITE',
        ),
    ]
