# Generated by Django 5.0.7 on 2024-08-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycarrier', '0011_remove_employer_post_a_job_job_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer_post_a_job',
            name='JOB_DESCRIPTION',
            field=models.CharField(max_length=400),
        ),
    ]
