# Generated by Django 5.0.7 on 2024-08-21 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycarrier', '0012_alter_employer_post_a_job_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer_post_a_job',
            name='JOB_DESCRIPTION',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='employer_post_a_job',
            name='JOB_EDUCATION_EXPERIENCE',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='employer_post_a_job',
            name='JOB_REQUIRED_KNOWLEDGE',
            field=models.CharField(max_length=500),
        ),
    ]
