# Generated by Django 5.0.7 on 2024-08-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycarrier', '0020_user_jobseeker_jobseeker_skill2'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_jobseeker',
            name='jobseeker_state',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
