# Generated by Django 5.0.7 on 2024-08-23 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycarrier', '0026_user_jobseeker_jobseeker_resume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_jobseeker',
            old_name='jobseeker_skill1',
            new_name='jobseeker_skills',
        ),
        migrations.RemoveField(
            model_name='user_jobseeker',
            name='jobseeker_skill2',
        ),
    ]
