# Generated by Django 5.0.7 on 2024-08-26 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycarrier', '0027_rename_jobseeker_skill1_user_jobseeker_jobseeker_skills_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobseeker_apply_job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DETAILS_OF_EMPLOYER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycarrier.user_employer')),
                ('DETAILS_OF_JOB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycarrier.employer_post_a_job')),
            ],
        ),
    ]
