# Generated by Django 5.0.7 on 2024-08-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycarrier', '0028_jobseeker_apply_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker_apply_job',
            name='user',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
