# Generated by Django 5.0.7 on 2024-08-26 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycarrier', '0029_jobseeker_apply_job_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker_apply_job',
            name='DETAILS_OF_EMPLOYER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycarrier.user_jobseeker'),
        ),
    ]
