# Generated by Django 5.0.7 on 2024-08-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycarrier', '0030_alter_jobseeker_apply_job_details_of_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker_apply_job',
            name='status',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
