# Generated by Django 5.0.7 on 2024-08-29 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycarrier', '0031_jobseeker_apply_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker_apply_job',
            name='reject',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobseeker_apply_job',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
