# Generated by Django 5.0.7 on 2024-09-11 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycarrier', '0034_alter_jobseeker_apply_job_details_of_employer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseeker_apply_job',
            old_name='DETAILS_OF_EMPLOYER',
            new_name='DETAILS_OF_EMPLOYEE',
        ),
    ]
