# Generated by Django 5.0.6 on 2024-09-18 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycarrier', '0035_rename_details_of_employer_jobseeker_apply_job_details_of_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_employer',
            name='verify',
            field=models.BooleanField(default=False),
        ),
    ]
