"""
Django settings for carrierguide project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-md)&6ayleu@!c*^1*)!s#%(w-cv2b)9h=a95bs_4ovx!-yf_2-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

<<<<<<< HEAD
ALLOWED_HOSTS = []
=======
ALLOWED_HOSTS = ['*','192.168.29.90']
>>>>>>> 0133ccfa30fe07cdb7d6867cc3c5465c95f493f4


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mycarrier',
<<<<<<< HEAD
]

MIDDLEWARE = [
=======
    'storages',

    
    
   
    
]

MIDDLEWARE = [

    "whitenoise.middleware.WhiteNoiseMiddleware",
>>>>>>> 0133ccfa30fe07cdb7d6867cc3c5465c95f493f4
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'carrierguide.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                
            ],
        },
    },
]

WSGI_APPLICATION = 'carrierguide.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

<<<<<<< HEAD
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME':'carrierguide',
        'USER': 'root',
        'PASSWORD':'',
        'HOST':'localhost',
        'PORT':3306,

=======
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME':'carrierguide',
#         'USER': 'root',
#         'PASSWORD':'',
#         'HOST':'localhost',
#         'PORT':3306,

#     }
# }


#aws
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'mydata',
        'USER': 'mycarrier',
        'PASSWORD': 'Hermia_jaison26',
        'HOST': "carrierguide.crgqgc6g0xfo.eu-north-1.rds.amazonaws.com",
        'PORT': 5432,
>>>>>>> 0133ccfa30fe07cdb7d6867cc3c5465c95f493f4
    }
}




<<<<<<< HEAD
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Replace with your email host
EMAIL_PORT = 587  # Replace with your email port
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'hermiajaison26@gmail.com'  # Replace with your email
EMAIL_HOST_PASSWORD = 'bxsh pohs rjee jbnl' 
=======
# aws S3

AWS_ACCESS_KEY_ID = "AKIAQWHCQINAGD2NEAIF"
AWS_SECRET_ACCESS_KEY = "YKwXk0QMqjUvqJhUQlKRAzUuBz1c8nmGyi+KieRf"
AWS_STORAGE_BUCKET_NAME = "carrierbucket"
AWS_S3_REGION_NAME = "eu-north-1"
AWS_S3_SIGNATURE_NAME = 's3v4',
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL =  None
AWS_S3_VERITY = True
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

# AWS_S3_CUSTOM_DOMAIN = os.environ.get('AWS_S3_CUSTOM_DOMAIN')
# Use S3 for storing static files
# STATIC_URL = f'https://{AWS_STORAGE_BUCKET_NAME}.eu-north-1.amazonaws.com/static/'
# STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

# Use S3 for storing media files
# MEDIA_URL = f'https://{AWS_STORAGE_BUCKET_NAME}.eu-north-1.amazonaws.com/media/'

# AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
>>>>>>> 0133ccfa30fe07cdb7d6867cc3c5465c95f493f4



# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
<<<<<<< HEAD
=======






EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'hermiajaison26@gmail.com'
EMAIL_HOST_PASSWORD = 'lzpo voos efok athk'

# Twilio Credentials
TWILIO_ACCOUNT_SID = 'AC28d188f3650e9fc9d27a3490ac945de6'
TWILIO_AUTH_TOKEN = '690e65bab8e0a5cc07b1ed84ba618de5'
TWILIO_PHONE_NUMBER = '+18286496019'
>>>>>>> 0133ccfa30fe07cdb7d6867cc3c5465c95f493f4
